features/rewards/components/rewardsTable/RewardsTable.tsx
features/withdrawals/claim/form/requests-list/request-item.tsx
package.json
shared/hook-form/controls/token-select-hook-form.tsx
yarn.lock

- Updated UI kit, now it exports proper types
- Fixed bug with rewards table
Before:
After:
No visual or functional changes are expected, the only difference is reward table padding

Update UI kit types on staking widget

---

package.json
yarn.lock

Fixed up dependabot warning:
- upped minor `next` version
- resolved `postсss` version 
Web app should look and function the same. Only minor health check required.

Package versions

---

features/wsteth/shared/form-controller/form-controller.tsx
pages/index.tsx
pages/withdrawals/[mode].tsx
pages/wrap/[[...mode]].tsx
shared/components/footer/footer.tsx
shared/hooks/useWeb3Key.ts
utils/getErrorMessage.ts

- now stake,wrap and withdrawal pages remount completely if chain or address changes, eliminating disconnect edge cases 
- added case for ledger live + wc transaction reject
- added footer version case for develop and staging environments

Add widget remount on wallet change

---

config/matomoClickEvents.ts
features/withdrawals/request/form/controls/token-amount-input-request.tsx
shared/forms/components/input-amount/input-amount.tsx
shared/forms/components/input-decorator-max-button/input-decorator-max-button.tsx

Max button in withdrawals request form

feat: add withdrawalMaxInput matomo event, removed calculateRewards matomo event

---

next.config.mjs
package.json
utilsApi/withCSP.ts

When we use `yarn dev-ipfs` we still use Next.js HMR, which works over `http` and `ws`.
Without this fix a IPFS mode not works on http://localhost in Safari and Firefox (possible another browsers).
Not actual for Chrome (works any way).

fix: next.js HMR for IPFS dev

---

.env.example
config/rpc.ts
config/types.ts
env-dynamics.mjs
utils/parse-env-config.ts

Refactor:
- The ENV `PUBLIC_UNSAFE_SETTINGS_PREFILL_RPC` to `PREFILL_UNSAFE_EL_RPC_URLS`
- The dynamic ENV `settingsPrefillRpc: string` to `prefillUnsafeElRpcUrls: string[]`

refactor: public unsafe settings prefill RPC as array

---

features/home/one-inch-info/hooks.ts
features/withdrawals/hooks/useWithdrawalRates.ts

Just small fix of props order when execute getOneInchRateApiUrl

fix: props order when execute getOneInchRateApiUrl

---

features/home/lido-stats/lido-stats-item.tsx
features/home/lido-stats/lido-stats.tsx

LidoStats has been separated to small components:
- LidoStats
- LidoStatsItem

refactor(LidoStats): separate to small components

---

config/rpc.ts
features/settings/settings-form/settings-form.tsx
pages/settings.tsx
shared/components/header/components/header-wallet.tsx

- made `RPC settings` page functionality, but disabled for infra version (return 404 page)
- made opportunity to use saved client RPC

feat: make RPC settings page for infra version

---

next.config.mjs
scripts/generate-build-id.mjs

- Added generation of build id from commit hash
- Checked that build files don't change between builds with custom id
- If build-info.json is not filled out, fallback to next default build id
Should not affect in any way. Only health check required.

Build id generation

---

features/home/home-page-regular.tsx
features/ipfs/home-page-ipfs.tsx
pages/index.tsx

- `HomePageIpfs` moved to `features/ipfs`
- `HomePageRegular` moved to `features/home`

refactor: move home pages to features

---

pages/api/oneinch-rate.ts
pages/api/short-lido-stats.ts
utilsApi/nextApiWrappers.ts

Set a CORS origin '*' and HttpMethodGuard 'GET' for:
- /api/oneinch-rate
- /api/short-lido-stats

feat: set a CORS and HttpMethodGuard for /api/oneinch-rate and /api/short-lido-stats

---

features/withdrawals/hooks/useWithdrawalRates.ts
features/withdrawals/request/form/options/dex-options.tsx
features/withdrawals/request/form/options/options-picker.tsx

Removes 1inch dex from withdrawals list
Just code removal
Only withdrawals page is affected.

Hot fix: Remove 1inch withdrawals integration

---

package.json
yarn.lock

Resolves SI-1081
1. Contains this fix for autoconnect: https://github.com/lidofinance/reef-knot/pull/106
2. Removes some wallets: mathwallet, zerion, blockchain.com, phantom, taho, zengo.

ReefKnot: hotfix for autoconnect, remove some wallets

---

utils/getErrorMessage.ts

Added error message when permit signature is invalid. 
How to reproduce:
1. start withdrawing
2. sign permit but don't sign tx yet
3. open another window
4. go trough full withdrawal flow (but don't sign tx from step 2)
5. sign tx from step 2

Added permit signature error

---

features/rewards/components/rewardsListContent/RewardsListContent.tsx
features/rewards/components/rewardsListContent/RewardsListContentStyles.ts
features/rewards/components/rewardsListHeader/styles.ts

Reward history filters fixed on mobile layout

style: mobile mode for reward history filters

---

features/home/one-inch-info/one-inch-info.tsx
features/rewards/fetchers/requesters/json/backend.ts
features/rewards/hooks/useRewardsDataLoad.ts
features/withdrawals/hooks/useWithdrawalRates.ts
features/withdrawals/request/form/options/dex-options.tsx
shared/hooks/useLidoStats.ts

Fix CORS ('cause it have been redirects to urls with `/` at end):
- correct a `api/oneinch-rate/` url in ETH widget IPFS mode
- correct a `api/short-lido-stats/` url in ETH widget IPFS mode
- correct a `api/reward/` url in ETH widget IPFS mode

fix(cors): correct a api urls in ETH widget IPFS mode

---

utilsApi/nextApiWrappers.ts

Unparsable url exeption in rpc eth_call metrics fixed

fix: handle unparsable referer in rpc eth call metrics

---

features/stake/stake-form/stake-form-context/stake-form-context.tsx
features/stake/stake-form/stake-form-context/types.ts
features/stake/stake-form/stake-form-modal.tsx

Fixed incorrect balance passthrough for stake success modal. ETH balance was passed instead of stETH.

Fix stake modal balance token

---

shared/components/layout/header/components/navigation/navigation.tsx

Fixed active navlink
Needs recheck for infra/ipfs

fix: navlink active for home page

---

shared/components/switch/styles.tsx
shared/components/switch/switch-item.tsx

Fix warning 'Received  `true` for a non-boolean attribute `active` ...'.
Check `WRAP` and `WITHDRAWALS` pages.

refactor(SwitchItem): use transient props for `active`

---

features/wsteth/unwrap/unwrap-form/unwrap-form.tsx
features/wsteth/wrap/wrap-form/wrap-form.tsx
shared/banners/l2-wsteth/l2-wsteth.tsx

"Learn more" link at the L2 banner on "Unwrap" page uses `eth_widget_banner_l2_unwrap`

fix: matomo event name of l2 banner link on unwrap page

---

features/stake/stake-form/stake-form-modal.tsx
features/withdrawals/claim/tx-modal/tx-claim-modal.tsx
features/withdrawals/request/tx-modal/tx-request-modal.tsx
features/withdrawals/request/tx-modal/tx-request-stage-success.tsx
features/withdrawals/shared/tx-stage-modal/stages/tx-stage-pending.tsx
features/withdrawals/shared/tx-stage-modal/stages/tx-stage-sign.tsx
features/withdrawals/shared/tx-stage-modal/stages/tx-stage-success.tsx
features/wsteth/unwrap/unwrap-form/unwrap-form-tx-modal.tsx
features/wsteth/wrap/wrap-form/wrap-form-tx-modal.tsx
shared/components/tx-stage-modal/text-utils.tsx
shared/components/tx-stage-modal/tx-stage-modal.tsx
utils/formatBalance.ts

> If after the comma the user texts bigger than 4 zero [0.000001], need display all the number after comma or bring solution to display it more friendly

fix: token number format in stage modal

---

pages/api/oneinch-rate.ts
test/consts.ts

[fix] disable oneinch endpoint

---

shared/components/layout/footer/styles.tsx

> We have requested from the design requirements for footer design to be consistent for all widgets and products.

style: footer design updated

---

features/stake/stake-form/stake-form-info.tsx
features/wsteth/unwrap/unwrap-form/unwrap-stats.tsx
features/wsteth/wrap/wrap-form/wrap-stats.tsx
shared/formatters/format-token.tsx
utils/formatBalance.ts

> Need to add hovers on Stake page, Wrap page, Unwrap page, Request page to "You will receive" value

Add hover on you will receive value

---

config/tx.ts
features/stake/stake-form/stake-form-context/types.ts
features/stake/stake-form/stake-form-context/validation.ts
features/withdrawals/claim/claim-form-context/claim-form-context.tsx
features/withdrawals/claim/claim-form-context/types.ts
features/withdrawals/claim/claim-form-context/validation.ts
features/withdrawals/claim/form/requests-list/requests-empty.tsx
features/withdrawals/claim/form/requests-list/requests-list.tsx
features/withdrawals/request/form/transaction-info.tsx
features/withdrawals/request/request-form-context/types.ts
features/withdrawals/request/request-form-context/use-validation-context.ts
features/withdrawals/request/request-form-context/validators.ts
features/wsteth/unwrap/hooks/use-unwra-form-validation-context.ts
features/wsteth/unwrap/hooks/use-unwrap-gas-limit.ts
features/wsteth/unwrap/hooks/use-unwrap-tx-processing.ts
features/wsteth/unwrap/unwrap-form-context/types.ts
features/wsteth/unwrap/unwrap-form-context/unwrap-form-context.tsx
features/wsteth/unwrap/unwrap-form-context/unwrap-form-validators.tsx
features/wsteth/wrap/hooks/use-wrap-form-network-data.ts
features/wsteth/wrap/hooks/use-wrap-form-validation-context.ts
features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
features/wsteth/wrap/wrap-form-context/types.ts
features/wsteth/wrap/wrap-form-context/wrap-form-context.tsx
features/wsteth/wrap/wrap-form-context/wrap-form-validators.ts
features/wsteth/wrap/wrap-form/wrap-stats.tsx
shared/components/allowance-data-table-row/allowance-data-table-row.tsx
shared/components/allowance-data-table-row/index.ts
shared/hook-form/validation/validate-stake-eth.ts

For All forms:
For Wrap:
For Claim:
- With async validation contexts I moved out always available parts like `active`. This allows us to have only `active=true` things in asyncContext(e.g. balance) and in case of `active=false` run basic input validation AND error out silently into **dummy** field. 
What that gives us:  When wallet is not connected user still has basic validation, but even if validation passes - `active=false` sets errors for invisible field, so you cannot submit even with ENTER. Striking user with basic validation first, allows us to hide that we might not have yet loaded balances, stakeLimit and else
- Also moved around some stuff to avoid useless Number-> BigNumber conversion
All forms are touched, but only as far as validation and errors. No need to test TXs full flow …

Validation messages and edge-cases

---

features/withdrawals/hooks/useWithdrawalRates.ts
features/withdrawals/request/form/options/dex-options.tsx

Withdrawal aggregator should be hidden only when respond error code is 500

Change the hiding rule of withdrawal aggregators

---

features/withdrawals/request/form/options/lido-option.tsx
features/withdrawals/request/wallet/wallet-queue-tooltip.tsx
shared/components/only-infra-render/index.ts
shared/components/only-infra-render/only-infra-render.tsx
shared/components/only-ipfs-render/index.ts
shared/components/only-ipfs-render/only-ipfs-render.tsx

Links to FAQ from IPFS widget removed:
Request page -> Withdrawal mode -> link to "Other factors"
Request page -> Lido option -> link to "FAQ"

feat: components for only infra or ipfs render modes

---

shared/hooks/use-token-max-amount.ts

> if user has more ETH than the limit, if he clicks to Max button, the amount to be <LIMIT - GAS> 
> Expected result: the amount equals with limit

fix: use token max amount limit after gas

---

features/ipfs/outdated-hash-banner/use-ipfs-hash-check.ts

Changes .link to .limo in ens integration. Infra version not affected.

[fix]change eth.link to eth.limo

---

shared/hooks/use-mainnet-static-rpc-provider.ts

In `useMainnetStaticRpcProvider` wrong rpc was passed to provider.
Functionality affected:
- On testnets where mainnet RPC is used.
- IPFS upgrade banner, ens look up

Fix Mainnet RPC Url

---

utils/get-open-ocean-rate.ts

We need to get maxFeePerGas from gasPrice endpoint and pass it as gasPrice param in quote endpoint

fix: openocean gas price source updated

---

package.json
shared/wallet/connect-wallet-modal/connect-wallet-modal.tsx
shared/wallet/connect/connect.tsx
yarn.lock

This PR solves issue with `isAutoConnectionSuitable` not working properly, which causes issues with autoConnect and transactions.

fix: use reef-knot 2.1.1 and useAutoConnectCheck

---

shared/wallet/connect/connect.tsx

Rollback "Connect wallet" eagerConnect behaviour as a temporary solution for the issue with Accept Terms modal and autoConnect.

fix: rollback "Connect wallet" eagerConnect behaviour

---

providers/web3.tsx

Disable wagmi default autoConnect, because it duplicates our custom Reef Knot autoConnect, which causes issues.

fix: disable wagmi autoConnect

---

features/ipfs/rpc-availability-check-result-box/rpc-availability-check-result-box.tsx

Resolves SI-1121
**Note!** https://github.com/lidofinance/docs/pull/332 must be released before this PR.
The task was to write an instruction about IPFS for our regular users and place a link to this instruction somewhere on IPFS version of the widget.
I place it here under "What is IPFS" link. Previously there was just "IPFS" labeled link to ipfs official docs.
The update is visible on IPFS version of the widget.
Maybe there is some better place for the instruction?

Add a link to IPFS instruction from lido docs

---

features/rewards/components/stats/Stats.tsx
features/rewards/components/stats/types.ts
features/rewards/features/top-card/top-card.tsx
features/rewards/hooks/use-laggy-data-wrapper.ts
features/rewards/hooks/use-rewards-balance-data.ts
features/rewards/hooks/use-steth-eth-rate.ts
features/rewards/hooks/useRewardsDataLoad.ts
providers/rewardsHistory.tsx

Steth balance persists on rewards history from previous request while address is incorrect
Using an approach that already was used for another reward history

Empty "stETH balance" when clear address input

---

features/ipfs/index.ts
features/ipfs/rpc-availability-check-result-box/rpc-availability-check-result-box.tsx
features/ipfs/security-status-banner/index.ts
features/ipfs/security-status-banner/use-remote-version.ts
features/ipfs/security-status-banner/use-version-check.ts
features/withdrawals/request/form/options/dex-options.tsx
global.d.ts
shared/components/layout/footer/footer.tsx
shared/components/layout/footer/link-to-ipfs.tsx
shared/components/layout/footer/styles.tsx
shared/components/layout/header/components/header-settings-button.tsx

For Infra: link to actual IPFS
For IPFS: link to docs
Also added types for svg imports.

feat: add link to ipfs

---

features/wsteth/wrap/hooks/use-wrap-tx-processing.ts

Fixed QA helper for Wrap eth.
`localStorage.setItem('mockLimitReached',true)`

fix: qa helper stake limit for wrap eth

---

features/ipfs/security-status-banner/security-status-banner.tsx
features/ipfs/security-status-banner/use-version-check.ts

Added banner for when infra version is unsafe but there is a safe version update available.
Can be tested with localStorage and qa helpers:
`mock-qa-helpers-security-banner-is-update-available` = `true`
`mock-qa-helpers-security-banner-is-version-unsafe` = `true`

feat: add infra update banner

---

features/withdrawals/request/withdrawal-rates/integrations.ts

In order to have the same rate on Lido UI and 1inch app, we need to change API navigation from "fusion mode" to “classic swap”.

feat: 1inch integration mode classic

---

features/withdrawals/hooks/useWaitingTime.ts

- change range `~1 - ${calcTime}` to single number `~${calcTime}`

feat: removed waiting time range

---

package.json
yarn.lock

The related PR in reef-knot: https://github.com/lidofinance/reef-knot/pull/135
Resolves SI-1354
This PR fixes a problem with wallet connection when the widget is embedded (opened in an iframe).
The problem is caused by our Safe Wallet detection, which looks like "if the widget is opened in iframe, then it is Safe Wallet". The detection happens on the widget page load, returns `true`, which triggers auto connection logic. The "Accept Terms" modal is displayed, but the "Connect wallet" button does nothing, because it awaits Safe Wallet to be accessible, but it isn't.
Previously, we had the widget embedded on this docs page: https://docs.lido.fi/integrations/wallets
And it was possible to connect a wallet on this page. But it was reported that it is not possible anymore, so we had to …

Fix wallet connection issue with iframes (reef-knot v4.1)

---

config/groups/stake.ts
features/stake/stake-form/use-stake.ts
features/stake/stake-form/utils.ts

Adds metric indicator for stake tx on widget. 
- send stake transaction with referral or without
- check raw tx call data on etherscan
- tx must succeced, no error
- you should see `01` at the end of data after ref address(or zero address)
Example:

Stake referral metric

---

features/stake/stake-form/stake-form-context/stake-form-context.tsx
pages/index.tsx
yarn.lock

Fixed issue when after changing ref param, change would not reflect in code. Causing ref to be invalid or missing.
This might be caused by cloudfare caching ingoring query params + next.
Test on deployed envs, change ref in url from valid(address or ens) to invalid (`?ref=aboba`), reload page and try to stake. With invalid ref you will get error when staking.
Also you can check metamask window, it should have ref address here at the end of `HEX DATA`

fix: ref param not parsing

---

features/withdrawals/request/form/options/dex-options.tsx
features/withdrawals/request/form/options/options-picker.tsx

- fixed best rate flashing loaders
- fixed double state in dex options

Fix invalid states in dex withdrawals

---

features/rewards/components/stats/Stats.tsx

Fixes "More info" link's href in the "Average APR" section on the `/rewards` page.
At the moment of writing, the `/ethereum#apr` is not working as expected, there is no such anchor on the page. But it will start working after the nearest landing release.

Fix: "more info" link href

---

features/rewards/components/rewardsTable/RewardsTable.tsx

Hide pagination on rewards page if pages < 2
Needs check on /rewards page

feat(rewards): hide pagination if pages < 2

---

features/withdrawals/claim/claim-form-context/claim-form-context.tsx
features/withdrawals/hooks/contract/useWithdrawalsData.ts

Enforce sorting for all requests ids in claim data to ensure withdrawal requests order.

[fix] claim request sorting

---

features/stake/stake-faq/list/what-is-lido.tsx

Fix: remove solana from FAQ

---

pages/api/eth-apr.ts
pages/api/eth-price.ts
pages/api/ldo-stats.ts
pages/api/lido-stats.ts
pages/api/lidostats.ts
pages/api/rpc.ts
pages/api/sma-steth-apr.ts
pages/api/totalsupply.ts

We use `httpMethodGuard` middleware for some API methods to allow only specific HTTP methods. But some endpoints, specifically `/api/rpc`, are not guarded from the widget side. This leads to errors in server logs when some bots or script kiddies are trying to send requests with incorrect HTTP methods to our endpoints.
Please, check that I used correct HTTP methods for the guards.
You can check that `/api/rpc` endpoint works as expected.
Some other endpoints were guarded too, but they are deprecated, and I'm not sure, that you will be able to test them all:
- `/api/eth-apr`
- `/api/eth-price`
- `/api/ldo-stats`
- `/api/lido-stats`
- `/api/lidostats`
- `/api/sma-steth-apr`
- `/api/totalsupply`

Add httpMethodGuard middleware for api endpoints

---

features/stake/swap-discount-banner/integrations.tsx

Change the link of the "Get discount" button on the Stake page 1inch banner

fix: 1inch discount link

---

features/stake/stake-page.tsx
pages/rewards.tsx

Removing a dot symbols at the end of the page sub-titles

chore: consistency of last symbol-dot of sub-tittle of each page

---

features/rewards/components/addressInput/AddressInput.tsx
features/rewards/components/addressInput/types.ts
features/rewards/features/top-card/top-card.tsx
features/rewards/hooks/useGetCurrentAddress.ts
providers/rewardsHistory.tsx

Handle ENS errors better:
1. Holesky doesn't support ENS. If an error happened during ENS name resolving, show error message near the input. Infinite loader is fixed too. 
2. If there are no errors with ENS resolving, but the name simply wasn't found (e.g. it is not registered), show another error
The error 1 can be tested on testnet.
To check error 2 you should deploy the PR on mainnet.

Add better handling for ENS errors

---

features/withdrawals/request/wallet/wallet-steth-balance.tsx
features/withdrawals/request/wallet/wallet-wsteth-balance.tsx
features/wsteth/shared/wallet/wallet.tsx

Lowercase for "ETH/stETH/wstETH [B]alance" labels

chore: balance labels lowercased

---

features/wsteth/wrap/hooks/use-wrap-form-validation-context.ts
features/wsteth/wrap/wrap-form-context/types.ts
features/wsteth/wrap/wrap-form-context/wrap-form-validators.ts
shared/hook-form/validation/validate-stake-eth.ts

Fixes validation error when wallet is not connected on wrap form. Other forms also checked for this.
Error happened due to in not connected state form was trying to wait for account data like balance
Stake and wrap form validation touched. Pls check (un)connected state for them.

[fix] unconnected wallet for wrap form

---

providers/sdk-legacy.tsx

fix: use chainId for SDK only from supportedChainIds

fix: use chainId for SDK only from supportedChainIds

---

shared/components/layout/footer/external-link.tsx
shared/components/layout/footer/link-to-ipfs.tsx
shared/components/layout/footer/styles.tsx
shared/components/layout/header/components/navigation/styles.tsx
shared/components/layout/header/styles.tsx
styles/constants.ts

Resolves SI-1334, Si-1324
- Place icons in the mobile bottom navigation at the same distance from each other
- Fix mobile bottom navigation for iPhone X and newer with "Single Tab" option enabled in Safari settings.
- refactor header and footer styles: use constants

Update header and footer styles, fix mobile nav on iPhones

---

shared/wallet/wallet-modal/wallet-modal.tsx

The issue:
1. A user connects a wallet and opens a modal with details about the connected wallet.
2. The user somehow disconnects the wallet (plugs off ledger, disconnects via browser extension wallet UI, etc.)
3. The modal stays opened but becomes broken
The PR fixes the issue by closing the modal in event of wallet's address became unavailable.
Actually, the initial issue can be reproduced with any wallet, including MetaMask browser extension:
1. Connect wallet
5. Open modal with account address, "Connected with ..." and "Disconnect" button
6. Go to MetaMask extension screen, find "Connected sites" in a dropdown menu, choose it and disconnect from the widget
7. So, we disconnected a wallet while the Wallet Modal was opened – the issue reproduced

Close WalletModal if a wallet was disconnected

---

shared/transaction-modal/tx-stages-composed/tx-stage-operation-succeed-balance-shown.tsx

Adds "Add tokens to wallet" button on the Stake and Wrap pages after successful transaction.
Adds stETH or wstETH respectively.
Resolves SI-1409
See links to Figma in the task.

Add "add token" button after successful tx

---

config/rpc/index.ts
providers/web3.tsx

The Polygon Mumbai chain was added when we updated from WC v1 to WC v2 a year ago. At that moment, we had issues with Zerion and Trust wallets connected via WC v2, adding an extra chain was a workaround.
The issue was fixed in wagmi 1+, so I'm removing this extra chain from the code after our recent update to wagmi v2.
I guess we can check that Trust wallet works okay via WalletConnect.

Remove Mumbai chain

---

utilsApi/nextApiWrappers.ts

This PR should solve this kind of errors, which arrives in server logs on testnet:
```
TypeError: Cannot read properties of undefined (reading '******************************************')
at /app/.next/server/chunks/299.js:4754:136
at Array.forEach (<anonymous>)
at collectRequestAddressMetric (/app/.next/server/chunks/299.js:4750:11)
```
This PR adds a small additional check, nothing to test here

Fix: error in logs from collectRequestAddressMetric on testnet

---

package.json
yarn.lock

Updates reef-knot, contains these changes:
- https://github.com/lidofinance/reef-knot/pull/141
- https://github.com/lidofinance/reef-knot/pull/148
- https://github.com/lidofinance/reef-knot/pull/150
- https://github.com/lidofinance/reef-knot/pull/151
Removes yarn resolutions for:
- `@ledgerhq/hw-transport`
- `@ledgerhq/hw-transport-webhid`

Reef Knot 5.2.0, ledger hw deps updated

---

features/stake/stake-form/hooks.ts
features/stake/stake-form/use-stake.ts
features/stake/stake-form/utils.ts
features/withdrawals/hooks/contract/useClaim.ts
features/withdrawals/hooks/contract/useRequest.ts
features/wsteth/unwrap/hooks/use-unwrap-tx-processing.ts
features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
features/wsteth/wrap/hooks/use-wrap-tx-processing.ts
shared/hooks/useApprove.ts
utils/apply-gas-limit-ratio.ts
utils/estimate-gas.ts
utils/send-tx.ts

- use sendTx callback for unified tx sending
- remove usage of walletRPC during tx preparation to prevent unsynced/broken nodes messing up
-  double estimate gas flow to distinguish between` not enough ether` and tx failing 
Unfortunately, this touches ALL TXs.
Please check multisigs.

[fix] remove usage of wallet rpc during tx

---

features/stake/stake-form/wallet/wallet.tsx
features/withdrawals/claim/wallet/wallet.tsx
features/withdrawals/request/wallet/wallet.tsx
features/wsteth/shared/wallet/wallet.tsx
shared/wallet/l2-fallback/l2-fallback.tsx

Add operation to text on l2 banner on each page
**stake**
**wrap/unwrap**
**withdrawals request**
**withdrawals claim**

feat: add operation to text on l2 banner on each page

---

shared/wallet/l2-fallback/l2-fallback.tsx

Fix matomo event on L2 banner
Just click to 'Lido on L2 opportunities' on L2 banner

fix: matomo event

---

test/consts.ts
test/smoke.spec.ts

Removed checks of some api methods (who were migrated to eth-api)

fix: tests before to remove some api methods

---

pages/api/eth-apr.ts
pages/api/eth-price.ts
pages/api/ldo-stats.ts
pages/api/lido-stats.ts
pages/api/lidostats.ts
pages/api/sma-steth-apr.ts
pages/api/totalsupply.ts
utilsApi/nextApiWrappers.ts

- Add cors headers to all external endpoints
- allow correct OPTIONS header behavior with method guard
Endpoints to test on /api:
- eth-apr
- eth-price
- ldo-stats
- lido-stats
- lidostats
- sma-steth-apr
- totalsupply
Should have cors headers. Respond correctly to OPTIONS http request.

Add Cors to all external endpoints

---

features/rewards/utils/genExportData.ts

Use ISO8601 date when exporting rewards to csv

fix: use ISO for dates in rewards csv

---

tsconfig.json

Changed TS compilerOptions.moduleResolution from `node` to `nodenext`
Check all widget critical functional
P.S. successful local tested on the sepolia network

chore: moduleResolution is nodenext

---

consts/matomo-click-events.ts
features/stake/stake-form/hooks/use-tx-modal-stages-stake.tsx
features/wsteth/wrap/hooks/use-tx-modal-stages-wrap.tsx
shared/banners/vaults-banner-info/const.ts

- change wrap success banner as it is on stake success banner
- add matomo events on "Explore defi options" on success banner

feat: change wrap success banner

---

features/rewards/components/address-input/address-input.tsx
features/rewards/components/rewardsListContent/RewardsListContent.tsx
features/rewards/components/rewardsListContent/RewardsListsUnsupportedChain.tsx
features/rewards/components/rewardsListHeader/RewardsListHeader.tsx
features/rewards/components/stats/average-apr-block.tsx
features/rewards/components/stats/steth-balance-block.tsx
features/rewards/components/stats/steth-price-block.tsx
features/rewards/components/stats/steth-rewarded-block.tsx
features/rewards/features/top-card/top-card.tsx
features/rewards/features/top-card/wallet.tsx
features/rewards/hooks/useGetCurrentAddress.ts
providers/rewardsHistory.tsx

- Show the 'unsupported chain' banner  if connected wallet and unsupported chain.
- fix: Return data-testid="inputSection".
- fix: Return showing filters, currency select and export button for not connected wallets state.
- not connected wallet
- unsupported chain OR supported chain
- empty address input
---
- connected wallet
- unsupported chain
- there aren't rewards
---
a 'unsupported chain' text instead of rewards table
---
- connected wallet (supported chain) OR not connected wallet
- address input was filled by user --> there are rewards

feat: return unsupported banner to reward page

---

features/withdrawals/hooks/useTvlError.ts
features/withdrawals/hooks/useTvlMessage.ts
features/withdrawals/request/form/controls/input-group-request.tsx
features/withdrawals/request/form/controls/token-amount-input-request.tsx
features/withdrawals/request/form/options/dex-options/dex-options.tsx
features/withdrawals/request/form/options/options-picker.tsx
features/withdrawals/request/withdrawal-rates/use-withdrawal-rates.ts

If withdrawal request input value is larger than TVL then '–' is displayed as changing rate.

fix: do not send dexes rate request if tvl error occured

---

features/withdrawals/claim/claim-form-context/claim-form-context.tsx
features/withdrawals/claim/claim-form-context/use-max-selected-count.ts
features/withdrawals/claim/form/requests-list/request-item.tsx
features/withdrawals/withdrawals-constants/index.ts

Tooltip for when ledger clear sign only allows 2 requests claim
Double checked this restriction, if you give more requests only 2 will be displayed in ledger
Only in Ledger Live

feat: ledger live claim tooltip

---

IPFS.json
assets/icons/lido-multichain/mode.svg
config/external-config/types.ts
config/external-config/utils.ts
config/groups/revalidation.ts
consts/chains.ts
consts/external-links.ts
shared/hooks/use-dapp-status.ts
shared/wallet/lido-multichain-fallback/lido-multichain-fallback.tsx
shared/wallet/lido-multichain-fallback/styles.tsx

- Mode Network multichain fallback banner.
- Move banner chain ids to IPFS.json
Because we moved all multichain banner chainIDs to config, until this pr is merged into main(with updated config), no multichain banners will show on this code by default.
To enable banners:
``` ts
localStorage.setItem('mock-qa-helpers-show-lido-multichain-banners-on-testnet',true)
```
Override github request in browser with **IPFS.json from this branch**. Currently config has Mode chain for testnet and not for mainnet. If you want to test on staging environment you will have to modify override and add Mode chain id to `"1"."config"."multiChainBanner"` array

feat: mode network multichain banner

---

features/wsteth/unwrap/unwrap-form/unwrap-stats.tsx
features/wsteth/wrap/wrap-form/wrap-stats.tsx

Fixes "You will receive" position on stake/wrap inconsistency

fix: make "you will receive" row always first

---

shared/components/layout/header/components/chain-switcher/components/select-icon-tooltip/styles.tsx

Changed the background for dark theme in ChainSwitcherTooltip

feat(ChainSwitcherTooltip): black bg for dark theme

---

features/wsteth/shared/wallet/wallet.tsx

fix: add testnet chain names in 'wrong network' banner

fix: add testnet chain names in 'wrong network' banner

---

features/withdrawals/request/form/paused-info.tsx

feat: pausedInfo for Sepolia

---

features/wsteth/shared/wallet/wallet.tsx
shared/hooks/useIsLedgerHardware.ts

Added text 'Optimism is currently not supported in Ledger Hardware.'

feat: optimism in Ledger Hardware text

---

features/rewards/components/errorBlocks/ErrorUnprocessable.tsx

Updated link in rewards error to correctly point to sdk docs

fix: sdk link in rewards page

---

package.json
yarn.lock

Resolves SI-1668
Brings this fix to the widget:
https://github.com/lidofinance/reef-knot/pull/176

reef-knot 5.7.4 (ledger fixes)

---

scripts/startup-checks/rpc.mjs
utilsApi/metrics/startup-checks.ts
utilsApi/metrics/startup-metrics.ts

Add a chainId to startup checks rpc
Added checks for all supported chain in startup checks rpc
Stop app if no RPC URLs found for chain
In logs you will see:
```
...
{..."msg":"[startupCheckRPCs] [chainId=17000] Working RPCs: 2"}
{..."msg":"[startupCheckRPCs] [chainId=11155111] Broken RPCs: 0"}
...
{..."msg":"[startupCheckRPCs] [chainId=11155111] Working RPCs: 1"}
{..."msg":"[startupCheckRPCs] [chainId=11155111] Broken RPCs: 0"}
...
{..."msg":"[startupCheckRPCs] [chainId=11155420] Working RPCs: 1"}
{..."msg":"[startupCheckRPCs] [chainId=11155420] Broken RPCs: 1"}
...
```
In metrics you will see:
```
eth_stake_widget_ui_startup_checks_rpc_failed{rpc_domain="<domain1_here>",chain_id="17000"} 0
eth_stake_widget_ui_startup_checks_rpc_failed{rpc_domain="<domain2_here>",chain_id="17000"} 0 …
```

feat: modify rpc startup check

---

features/wsteth/unwrap/hooks/use-unwrap-tx-on-l2-approve.ts
features/wsteth/unwrap/unwrap-form/unwrap-stats.tsx
features/wsteth/wrap/hooks/use-wrap-tx-on-l1-approve.ts
features/wsteth/wrap/wrap-form/wrap-stats.tsx
modules/web3/hooks/use-max-gas-price.ts
modules/web3/web3-provider/dapp-chain.tsx
shared/components/allowance-data-table-row/allowance-data-table-row.tsx
shared/components/data-table-row-steth-by-wsteth/data-table-row-steth-by-wsteth.tsx
shared/components/layout/header/components/chain-switcher/chain-switcher.tsx
shared/components/layout/header/components/chain-switcher/components/chain-switcher-options/chain-switcher-options.tsx
shared/components/layout/header/components/chain-switcher/components/chain-switcher-options/styles.tsx
shared/components/layout/header/components/chain-switcher/components/select-icon-tooltip/styles.tsx
shared/components/layout/header/components/chain-switcher/hooks/use-click-outside.ts
shared/components/layout/header/components/chain-switcher/styles.tsx
shared/hooks/txCost.ts

refactor: remake the ChainSwitcher to own code
**if the ChainType not matched:**
- refactor: show the allowance any way (also not connected wallet)
- refactor(wrap): show the 'stats'
- refactor(unwrap): show the 'stats'
**remake the ChainSwitcher to own code**
---
**Wallet is any supported ETH chain, widget switcher on Optimism type (tx for Optimism)**
---
**Wallet is any supported Optimism chain, widget switcher on ETH type (tx for ETH)**
---
**Wallet is not connected**
Based on the https://github.com/lidofinance/ethereum-staking-widget/pull/510
See the 'chainTypeChainId' and the 'isChainTypeOnL2' in the 'useDappChain'

refactor: l2 tech debt improvement

---

utils/getErrorMessage.ts

- handle permit signing reject(due to user or blind signing off) for Ledger Live
- no way to determine user or blind sign reject( but better than not enough ether for gas
- should be resolved once Ledger deploys permits metadata for stETH and wstETH

fix: update Ledger Live error handling

---

Dockerfile
features/wsteth/unwrap/hooks/use-unwrap-form-processing.ts
features/wsteth/unwrap/hooks/use-unwrap-gas-limit.ts
features/wsteth/unwrap/hooks/use-unwrap-tx-on-l2-approve.ts
features/wsteth/wrap/hooks/use-approve-gas-limit.tsx
features/wsteth/wrap/hooks/use-wrap-form-processing.ts
features/wsteth/wrap/hooks/use-wrap-form-validation-context.ts
features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
modules/web3/hooks/use-balance.ts
modules/web3/hooks/use-contract-address.ts
modules/web3/hooks/use-stETH-by-wstETH.ts
modules/web3/hooks/use-steth-contract-address.ts
modules/web3/hooks/use-wstETH-by-stETH.ts
modules/web3/hooks/use-wsteth-contract-address.ts
modules/web3/index.ts
modules/web3/web3-provider/dapp-chain.tsx
modules/web3/web3-provider/index.ts
modules/web3/web3-provider/lido-sdk-l2.tsx
modules/web3/web3-provider/lido-sdk.tsx
shared/hooks/use-token-address.ts
shared/hooks/useStakingLimitInfo.ts

Split the SDK provider to 2 providers (L1 and L2)
...

refactor: split the SDK provider to 2 providers (L1 and L2) 

---

consts/matomo-wallets-events.ts
package.json
yarn.lock

This update replaces XDEFI wallet with Ctrl (rebranding):
See https://github.com/lidofinance/reef-knot/pull/204

reef-knot 7.1.0 (xdefi -> ctrl)

---

config/groups/web3.ts

Increased AA_TX_POLLING_TIMEOUT to 3 minutes. This constant defines how long dapp awaits for AA action to be confirmed. 3 minutes is enough for most TXs to get confirmed and only timeout if erroneous wallet forgets about this tx.

fix: increase AA tx timeout

---

shared/transaction-modal/transaction-modal-content.tsx

A fix for a big padding on the top of the transaction modal.

Transaction modal upper space improved

---

features/wsteth/shared/wallet/wallet.tsx

Fixes Ledger notifications for L2s

Fix: Ledger notifications for L2s

---

modules/web3/web3-provider/web3-provider.tsx
package.json
yarn.lock

Resolves SI-1793
- downgrade viem to 2.22
- bump sdk to 4.3.0-alpha.2
- import Unichain from lido-ethereum-sdk instead of viem (temporary solution)

Hotifx for the Safe transactions issue

---

features/stake/stake-form/use-stake.ts
features/stake/stake-form/utils.ts

Resolves SI-1817
Fixes the issue, when it is not possible to stake if some incorrect ref is provided.
The logic of processing the provided ref address looks like this:
1. if the ref is an Ethereum address (0x...), then the ref is used as is
2. if the ref starts with 'http[s]://', then the ref is replaced with a fallback address
3. if the ref ends with 'lido.fi', then the ref is replaced with a fallback address
It is possible to pass ENS names as a ref. We assume that no one uses 'lido.fi' ENS name, because not all ENS names end with '.eth' and it is technically possible to have 'lido.fi' ENS name.
4. only in the end, after all other checks, we are trying to get ENS name using the provided ref. Because this request takes some time (5 seconds or so).
Checked with refs:
- `?ref=blog.lido.fi` …

Fix: staking with incorrect refs – rework getRefferalAddress

---

features/ipfs/security-status-banner/use-remote-version.ts

cf-ipfs.com gateway doesn't work.
dweb.link looks okay according to https://ipfs.github.io/public-gateway-checker/, the link will be:
https://bafybeiecvujvs74xvxgpwctmbfkcucazyaudmwuiw4wfv6ys7uio7o376u.ipfs.dweb.link/

Change cf-ipfs.com gateway with dweb.link

---

modules/web3/web3-provider/dapp-chain.tsx
shared/components/layout/header/components/chain-switcher/chain-switcher.tsx

Fixed display of chain names in the banner when the widget has test networks and hasn't
```SUPPORTED_CHAINS=1,17000,560048,11155111,10,11155420,1868,1946,130,1301``` with all testnets
```SUPPORTED_CHAINS=1,10,1868``` without testnets
```SUPPORTED_CHAINS=1,10,11155111``` with ethereum sepolia testnets
names for mainnet chains in the chain switcher

fix: chains naming

---

modules/web3/consts/chains.ts
modules/web3/web3-provider/dapp-chain.tsx
modules/web3/web3-provider/web3-provider.tsx
package.json
shared/components/layout/header/components/chain-switcher/chain-switcher.tsx
shared/wallet/fallback/useErrorMessage.ts
utils/etherscan.ts
yarn.lock

Consistency of network names in the "Wrong network..." and "Unsupported chain" banners.
And simple refactoring.
Wrong network banner
Template if `${chainType}`:
- Wrong network. Please switch to Ethereum in your wallet to to wrap.
- Wrong network. Please switch to Optimism in your wallet to to wrap.
- Wrong network. Please switch to Unichain in your wallet to to wrap.
- Wrong network. Please switch to Soneium in your wallet to to wrap.
Unsupported chain banner:
```
Unsupported chain. Please switch to Ethereum, Optimism, Unichain or Soneium in your wallet.
```
Wrong network banner
Templates if `${chainType}(${chain.name})`:
- Wrong network. Please switch to Ethereum(Hoodi) in your wallet to to wrap.
- Wrong network. Please switch to Optimism(OP Sepolia) in your wallet to to wrap.
- Wrong …

feat: add pretty chain name for the "Wrong network..." banner

---

modules/web3/hooks/use-is-smart-account.ts

Add check for delegated EOA, so they are not considered contracts in the `isContract` check

useIsSmartAccount – add check for delegated eoa

---

features/rewards/components/address-input/address-input.tsx
features/rewards/hooks/useGetCurrentAddress.ts

Fixes the issue when the `enter_address_manually` event fires together with the `enter_address_auto` event.

Fix: rewards enter_address_manually matomo event

---

IPFS.json

Set `disableSendCalls` feature flag = true, which DISABLES batching txs

Disable sendCalls batching (flag = true)

---

IPFS.json

Set disableSendCalls feature flag = false, which ENABLES batching txs

Enable sendCalls batching (flag = false)

---

modules/web3/web3-provider/dapp-chain.tsx

Fixes the issue (SI-1930) – "the stETH balance isn't displayed on the reward page without a connected wallet".
The issue comes from this change (line 241):
https://github.com/lidofinance/ethereum-staking-widget/commit/9be7291548f7e5d0fc022417bbb00b12142880a7#diff-a5c65cdd246477f648aa2b4bb9372bdcdba53da41756dfbb475640765850ca95R240-R241
**Reason:**
- `isChainMatched` is always false, when wallet is not connected
- `isSupportedChain` is always true, when wallet is not connected
-  `isSupportedChain` was replaced with `isChainMatched`, therefore `useQuery` getting the contract address is never `enabled` if wallet is not connected
**Solution:**
I decided to apply to isChainMatched the same logic that isSupportedChain uses — to always return true if the wallet is not connected.
An alternative …

Reward Page – fix stETH balance if wallet not connected

---

features/rewards/components/Date.tsx
features/rewards/utils/formatDate.ts
features/rewards/utils/fromUnixTime.ts
features/rewards/utils/genExportData.ts
package.json
yarn.lock

- remove date-fns dependency due to low usage, replace with custom utils
- should solve issue, when yarn wasn't able to fetch date-fns package archive during CI build
This change can affect dates on Reward history page
Expected result: no changes in the UI

Replace date-fns with custom date utilities

---

features/withdrawals/request/withdrawal-rates/integrations.ts

The PR changes "Go to 1inch" link on the withdrawals -> Use DEXes block

1inch – change swap link

---

package.json
yarn.lock

Updates reef-knot to the version where MM SDK is used to connect MetaMask
Uses reef-knot alpha version at first, to be updated to the stable version after tests
Uses reef-knot alpha version at first, to be updated to the stable version after tests

Enable MetaMask SDK

---

IPFS.json
config/external-config/types.ts
features/stake/stake-form/stake-form.tsx
modules/web3/web3-provider/lido-sdk.tsx
package.json
shared/banners/dual-governance-banner/blocked-state.tsx
shared/banners/dual-governance-banner/dual-governance-banner.tsx
shared/banners/dual-governance-banner/index.ts
shared/banners/dual-governance-banner/styles.ts
shared/banners/dual-governance-banner/warning-state.tsx
shared/hooks/useDGWarningStatus.ts
yarn.lock

The PR adds Dual Governance status banner.
**QA mocks in localstorage**
- `mock-qa-helpers-dg-banner-enabled` - to enable
- `mock-qa-helpers-dg-state` - can be "Warning" or "Blocked"
- `mock-qa-helpers-dg-current-veto-support-percent` - number, support percent displayed in the banner
**Feature flags that also can be used**
Use `dgBannerEnabled` boolean feature flag in IPFS.json to enable the feature.
Use `dgWarningState` boolean feature flags to trigger Blocked state banner and Warning state banner.

Dual Governance status banner

---

features/withdrawals/hooks/contract/useRequest.ts
features/wsteth/unwrap/hooks/use-unwrap-form-processing.ts
features/wsteth/unwrap/hooks/use-unwrap-tx-on-l2-approve.ts
features/wsteth/unwrap/unwrap-form-controls/amount-input-unwrap.tsx
features/wsteth/unwrap/unwrap-form-controls/submit-button-unwrap.tsx
features/wsteth/wrap/hooks/use-wrap-form-processing.ts
features/wsteth/wrap/hooks/use-wrap-tx-on-l1-approve.ts
features/wsteth/wrap/wrap-form-controls/submit-button-wrap.tsx
features/wsteth/wrap/wrap-form-controls/token-amount-input-wrap.tsx
modules/web3/hooks/use-is-smart-account.ts

- Fixes withdrawal request with pre-set allowance
- Fixes withdrawal request UI for EOAs with EIP-7702 delegation
- Fixes unwrap on L2s for EOAs with EIP-7702 delegation
- Make wrap, unwrap, withdraw UIs consistent for cases when a user must unlock tokens
- Unifies some code for wrap, unwrap and withdraw
**Safe Wallet – BEFORE** 
**Safe Wallet – AFTER**
**EOA, no delegation, L2 – BEFORE**
**EOA, no delegation, L2 – AFTER**
**EOA, delegation + batch txs, L2 – BEFORE**
**EOA, delegation + batch txs, L2 – AFTER**

Fixes for allowance and UI consistency

---

package.json
pages/_app.tsx
yarn.lock

- copies CookiesTooltip from lido-ui and modifies it – adds ability to hide the privacy notice link
- configures the updated component to hide the privacy notice link from the CookiesTooltip when the widget is in the IPFS mode

Remove link to privacy notice from cookies popup for ipfs mode

---

features/earn/shared/styles.ts
features/earn/vault-dvv/vault-page-dvv.tsx
features/earn/vault-ggv/consts.tsx
features/earn/vault-ggv/faq/ggv-faq.tsx
features/earn/vault-ggv/faq/list/index.ts
features/earn/vault-ggv/faq/list/who-is-curator.tsx
features/earn/vault-ggv/vault-card-ggv.tsx
features/earn/vault-ggv/vault-page-ggv.tsx
features/earn/vaults-list/vaults-list.tsx
features/rewards/components/stats/average-apr-block.tsx
features/stake/lido-stats/lido-stats.tsx
features/stake/stake-form/wallet/wallet.tsx
features/stake/stake.tsx
pages/rewards.tsx
shared/components/apr-disclaimer/apr-disclaimer.tsx
shared/components/apr-disclaimer/index.ts
shared/components/apr-disclaimer/styles.tsx
shared/components/index.ts

This pull request refactors and standardizes the APR disclaimer across the app, improving consistency and maintainability. The main change is the replacement of the old `VaultDisclaimer` component with a new, more general `AprDisclaimer` component, which is now used in multiple locations. Additionally, the GGV vault description is centralized for reuse, and APR labels are updated to include an asterisk for clarity.
**APR Disclaimer Refactor and Standardization**
* Replaced the `VaultDisclaimer` component with the new `AprDisclaimer` component, moving its implementation from `features/earn/shared/vault-disclaimer.tsx` to `shared/components/apr-disclaimer/apr-disclaimer.tsx`, and updated all usages throughout the app to use the new component. …

Add APR disclaimers, unify GGV description

---

pages/api/rpc.ts

fix: prevent duplicate metric registration by singleton-wrapping rpcFactory

fix: prevent duplicate metric registration by singleton-wrapping rpcFactory

---

IPFS.json

Related: https://github.com/lidofinance/ethereum-staking-widget/pull/775
Forgot to add the vault for mainnet too

Add 'strategy' vault to ipfs.json for mainnet
