.github/workflows/checks.yml

fix: update ci

---

shared/banners/l2-low-fee/l2-low-fee.tsx
shared/banners/l2-swap/l2-swap.tsx

fix: fix button color

---

.github/workflows/ci-preview-deploy.yml

Disable goerli branch for deploy to preview stand.

[Holesky] Update preview WF

---

pages/api/short-lido-stats.ts
test/config.ts
utilsApi/getLidoHoldersViaSubgraphs.ts
utilsApi/getTotalStaked.ts

- Fix tests config
- Fix api/short-lido-stats
- Now the data depends on chainId

fix: fix tests

---

pages/api/oneinch-rate.ts

Set CORS and httpMethodGuard for api/oneinch-rate

feat: set CORS and httpMethodGuard for api/oneinch-rate

---

package.json
yarn.lock

Updated @lidofinance/lido-ui with cookies fixes

chore: update @lidofinance/lido-ui with cookie fixes

---

config/urls.ts
features/home/stake-faq/list/how-can-i-get-steth.tsx
features/home/stake-faq/list/how-can-i-unstake-steth.tsx
features/ipfs/ipfs-info-box/ipfs-info-box.tsx
features/rewards/components/errorBlocks/ErrorBlockNoSteth.tsx
features/withdrawals/request/tx-modal/tx-request-stage-success.tsx
features/withdrawals/withdrawals-constants/index.ts
features/withdrawals/withdrawals-faq/list/convert-steth-to-eth.tsx
features/withdrawals/withdrawals-faq/list/convert-wsteth-to-eth.tsx
features/withdrawals/withdrawals-faq/list/how-long-to-withdraw.tsx
features/withdrawals/withdrawals-faq/list/how-to-withdraw.tsx
features/withdrawals/withdrawals-faq/list/separate-claim.tsx
features/withdrawals/withdrawals-tabs.tsx
features/wsteth/shared/wrap-faq/list/do_i_need_to_unwrap_my_wsteth.tsx
features/wsteth/shared/wrap-faq/list/how-can-i-get-wsteth.tsx
features/wsteth/shared/wrap-faq/list/how-could-i-unwrap-wsteth-to-steth.tsx
features/wsteth/wrap-unwrap-tabs.tsx
pages/_home/home-page-ipfs.tsx
pages/wrap/[[...mode]].tsx
shared/components/header/components/header-settings-button.tsx
shared/components/header/components/navigation/navigation.tsx
shared/hooks/use-router-path.ts
test/pages/widget.page.ts

Made storing urls in separate module.

refactor: storing urls in separate module

---

shared/components/switch/switch-item.tsx
shared/components/switch/utils.ts
shared/hooks/use-compare-with-router-path.ts
utils/compare-with-router-path.ts

It was refactored a checking active status in switch item component

refactor: check active in switch item component

---

package.json
yarn.lock

- https://github.com/lidofinance/reef-knot/pull/92
- Remove GameStop, Opera wallets, rework Brave:
https://github.com/lidofinance/reef-knot/pull/103

ReefKnot: handle connection errors in AcceptTermsModal, remove wallets

---

features/home/stake-form/stake-form.tsx

hot fix: disable stake banner

---

features/ipfs/ipfs-info-box/ipfs-info-box.tsx
features/ipfs/ipfs-info-box/styles.tsx
features/settings/settings-form/settings-form.tsx
features/settings/settings-form/styles.ts
pages/api/rewards.ts
shared/components/header/components/navigation/navigation.tsx
shared/components/link-arrow/link-arrow.tsx

Fixes for IPFS
Cors for api/rewards
Settings page FAQ refactoring

feat: fixes for ipfs, cors for rewards, settings page faq refactoring

---

shared/components/switch/styles.tsx

Fixed links hover style in switch-item in ledger live

fix: links hover style in switch-item in ledger live

---

features/home/home-page-regular.tsx
features/withdrawals/withdrawals-tabs.tsx
features/wsteth/wrap-unwrap-tabs.tsx
pages/rewards.tsx
shared/banners/goerli-sunset/goerli-sunset-banner.tsx
shared/banners/goerli-sunset/index.ts
shared/banners/goerli-sunset/styles.ts

Goerli sunset information banner

feat: goerli sunset banner

---

shared/components/layout/header/components/navigation/navigation.tsx

fix(nav link infra version): is active

fix(nav link infra version): is active

---

features/stake/stake-form/controls/stake-amount-input.tsx
features/stake/stake-form/controls/stake-submit-button.tsx
shared/components/layout/footer/footer.tsx
shared/components/layout/header/components/navigation/navigation.tsx

- set locator for Stake input
- set locator for Stake button
- set locator for Footer appVersion

Attributes update

---

package.json
yarn.lock

Includes:
- https://github.com/lidofinance/reef-knot/pull/105
- https://github.com/lidofinance/reef-knot/pull/107
- https://github.com/lidofinance/reef-knot/pull/108
Resolves SI-1133

reef-knot 1.13.0: Wallet Adapters for XDEFI, imToken, Trust, Coinbase

---

.github/workflows/ci-ens.yml

feat: add ENS workflow

---

features/rewards/fetchers/requesters/json/backend.ts
features/rewards/hooks/useRewardsDataLoad.ts
next.config.mjs
pages/api/oneinch-rate.ts
shared/hooks/useLidoStats.ts

Set trailingSlash: true only on IPFS mode
(https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash)

feat: set trailingSlash: true only on IPFS mode

---

.github/workflows/ci-ipfs-test-production.yml
.github/workflows/ci-ipfs-testnet.yml
.github/workflows/ci-ipfs.yml

Update workflow IPFS Providers envs

feat: update providers envs,

---

package.json
providers/web3.tsx
yarn.lock

Brings these changes from Reef Knot:
- https://github.com/lidofinance/reef-knot/pull/112
- https://github.com/lidofinance/reef-knot/pull/113

Use reef-knot 1.15

---

features/withdrawals/request/form/bunker-info.tsx
features/withdrawals/request/form/options/lido-option.tsx
features/withdrawals/request/wallet/wallet-queue-tooltip.tsx
features/withdrawals/withdrawals-faq/list/bunker-mode-reasons.tsx
features/withdrawals/withdrawals-faq/list/claimable-amount-difference.tsx
features/withdrawals/withdrawals-faq/list/withdrawal-period-circumstances.tsx
package.json
providers/index.tsx
providers/inpage-navigation.tsx
shared/components/accordion-navigatable/accordion-navigatable.tsx
shared/components/accordion-navigatable/index.ts
yarn.lock

FAQ click-following navigation

---

features/stake/stake.tsx
features/withdrawals/claim/claim.tsx
features/withdrawals/request/request.tsx
features/wsteth/wrap-unwrap-tabs.tsx

feat: remove faq from IPFS

---

IPFS.json

Updated IPFS.json to test ens upwards compatibility. No release required.

Update ipfs manifest

---

IPFS.json

Updated IPFS.json to test ens upwards compatibility. _(No release required.)_

Merge develope to main

---

.github/workflows/ci-ipfs.yml

Update ENV variables for Production Workflow. To be able to use different keys and namespaces for test and production environments.

fix: update prod ipfs wf envs

---

.github/workflows/ci-ipfs-goerli.yml

feat: add goerli ipfs wf

---

.github/workflows/ci-ipfs-goerli.yml

Add build-info to Goerli IPFS version

fix: add build info to goerli IPFS wf

---

.github/workflows/ci-ipfs-goerli.yml

Develop to main

---

.github/workflows/ci-ipfs-goerli.yml
.github/workflows/ci-ipfs.yml

fix: refactoring ipfs wf

---

.github/workflows/ci-ipfs-goerli.yml
.github/workflows/ci-ipfs.yml

fix: action links

---

package.json
yarn.lock

Fixes "Connect wallet" button in Eager Connection modal.

fix: use reef-knot 3.0.1

---

features/ipfs/security-status-banner/use-version-check.ts

Fix show verify banner before getting a response

fix: verify banner

---

package.json
yarn.lock

Ups reef-knot to new patch version.
Fixes after leger modal success connect, main modal also closes.

Up reef knot

---

features/stake/swap-discount-banner/swap-discount-banner.tsx
shared/banners/l2-banner/l2-banner.tsx
shared/banners/l2-banners/l2-after-stake.tsx
shared/banners/l2-banners/l2-after-wrap.tsx
shared/banners/l2-banners/l2-from-stake-to-wrap.tsx
shared/banners/l2-banners/l2-wsteth.tsx

- add attributes for 1inchBanner, l2 banner on stakePage
- rename testidWrap->tesid

Add attributes stakePage

---

features/withdrawals/withdrawals-constants/index.ts

chore: enable bebop

---

features/withdrawals/withdrawals-constants/index.ts

Merge develop to main

---

IPFS.json

Update IPFS manifest with new CIDs and leastSafeVersion

chore: update IPFS manifest

---

features/ipfs/rpc-availability-check-result-box/rpc-availability-check-result-box.tsx
features/withdrawals/request/withdrawal-rates/integrations.ts
utils/get-bebop-rate.ts

[fix] bebop params and ipfs text

---

package.json
yarn.lock

https://github.com/lidofinance/reef-knot/pull/134

feat: reef-knot v4.2.0 (deeplinks)

---

features/withdrawals/withdrawals-constants/index.ts

Returns paraswap to list of enabled integrations. 
No logic changes, just config change. Please check that dex is working properly.

Enable paraswap

---

consts/matomo-click-events.ts
features/stake/stake-faq/list/how-can-i-get-steth.tsx

Adds a link to ledger wallet to FAQ

feat: add link to ledger to FAQ

---

features/stake/stake-form/use-stake.ts
shared/hooks/useIsLedgerLive.ts

For ledger and ledger-live do not add suffix on stake to allow clear signing.
Test on ledger direct connection and ledger live.

[Fix] disable calldata suffix for ledger

---

features/stake/stake-form/use-stake.ts

- allow calldata marker for direct ledger connection (there is always blind signing)
- fix for multisig(safe) tx path to allow marker
Check only stake tx for marker:
- defautl(mm)
- ledger direct
- safe (you can use tenderly inspect to see stake calldata)

[fix] stake calldata marker for safe and ledger

---

CONTRIBUTING.md
SECURITY.md

docs: updated contributing doc

---

features/withdrawals/claim/claim.tsx
features/withdrawals/request/request.tsx
features/withdrawals/withdrawals-tabs.tsx
pages/withdrawals/[mode].tsx

Render a withdrawals FAQ on SSR
Just check that there isn't 'next.js hydration' error.

feat(wq pages): render FAQ on SSR

---

test/consts.ts

Fix api tests:
- /api/lidostats
- /api/ldo-stats

feat: add to tests.validationResult new field 'tsAdded'

---

config/feature-flags/utils.ts

Enables vault banners feature flag.

[chore] enable vaults banners

---

IPFS.json

if #344 is approved for testing this will add holesky config when pushed to main.

[chore] add config holesky manifest 

---

.env.example

Hosted service subgraph will not be available soon. So we need to remove example of it.

docs: sunrise hosted service subgraph

---

features/rewards/components/errorBlocks/ErrorRateLimited.tsx
features/rewards/components/rewardsListContent/RewardsListErrorMessage.tsx

- added rate limit error message

feat: added rate limit message

---

features/withdrawals/request/form/options/dex-options/dex-options.tsx

https://github.com/lidofinance/ethereum-staking-widget/assets/20888859/7f6437dc-6466-480b-ae89-26889f055958

fix: change text animation

---

consts/matomo-wallets-events.ts
features/stake/hooks.tsx
package.json
providers/sdk-legacy.tsx
providers/web3.tsx
shared/transaction-modal/transaction-modal.tsx
shared/transaction-modal/tx-stages-basic/icons.tsx
shared/wallet/fallback/useErrorMessage.ts
utilsApi/nextApiWrappers.ts
yarn.lock

feat: wagmi version updated

---

package.json
providers/sdk-legacy.tsx
yarn.lock

Fixing sdk legacy web3 provider instance value
Should fix bugs on ledger-live and missing add token button. May be also the solution for coin98 bug.

fix: sdk legacy web3 provider instance value

---

package.json
yarn.lock

Missing wallets modal metric events restored

fix: wallets modal metrics

---

features/withdrawals/withdrawals-constants/index.ts

chore: update dexes config

---

features/withdrawals/request/form/options/dex-options/styles.ts
features/withdrawals/request/form/options/styles.tsx
styles/global.ts

- fix styles to match design
- clean up and use css vars

[fix] Dex icon styles

---

utils/getErrorMessage.ts

Incorrect transaction rejection handling from WC + Safe fixed

fix: safe app user-cancelled transaction ui message

---

consts/matomo-click-events.ts

Incorrect matomo event for Bebop "Go to" link fixed

fix: incorrect matomo event for Bebop

---

consts/matomo-click-events.ts
consts/matomo-wallets-events.ts
package.json
shared/wallet/connect-wallet-modal/connect-wallet-modal.tsx
yarn.lock

feat: browser wallet and show more/less wallets metric events

---

pages/api/oneinch-rate.ts
pages/api/short-lido-stats.ts
pages/api/sma-steth-apr.ts
utilsApi/cached-proxy.ts

hot fix for deprecated api response timeout

fix: depreceated api response

---

shared/banners/vaults-banner-info/vaults-banner-info.tsx
shared/banners/vaults-banner-strategies/vaults-banner-strategies.tsx

feat: vault banners text updated

---

tsconfig.json

revert moduleResolution to node

feat: revert moduleResolution to node

---

config/groups/stake.ts
features/stake/stake-form/use-stake.ts
features/stake/stake-form/utils.ts
utils/apply-round-up-gas-limit.ts
utils/send-tx.ts

Round up the gas limit and change the fallback ref address for the stake transaction.
Check all wallets to ensure that they do not override the gas limit.

feat: stake tracking

---

package.json
yarn.lock

fix: reef-knot@5.5.4

---

IPFS.json

Changed IPFS config to test on develop and IPFS

chore: holesky test ipfs config

---

IPFS.json

revert test changes to holesky config

chore: revert config test

---

consts/matomo-click-events.ts
features/rewards/components/export/Export.tsx
features/rewards/components/rewardsListHeader/LeftOptions.tsx
features/rewards/components/rewardsListHeader/RightOptions.tsx

Rewards share tracking Matomo events

feat: rewards page matomo events

---

IPFS.json
config/external-config/types.ts
config/external-config/utils.ts
config/groups/revalidation.ts
consts/external-links.ts
shared/hooks/use-dapp-status.ts

feat: use config for multichain banner

---

config/groups/web3.ts
features/withdrawals/hooks/contract/useRequest.ts
features/wsteth/wrap/hooks/use-wrap-tx-approve.ts
features/wsteth/wrap/wrap-form-context/wrap-form-context.tsx
providers/web3.tsx
shared/hooks/use-allowance.ts
shared/hooks/use-balance.ts
test/consts.ts

- Higher intervals and better caching for useEthereumBalance because it causes rate limit on WC
- Tweaked down some agressive defaults.
- added allowance refetch after tx
- fixed events for allowance
- removed deprecated endpoints from tests

fix: higher block fetch interval

---

pages/_app.tsx

When returning 404, pageProps are undefined and it causes server error

404 internal server error

---

IPFS.json
pages/_app.tsx

Update config for sepolia deploy

---

abi/lidoLocator.abi.json
config/groups/web3.ts
features/rewards/hooks/use-steth-eth-rate.ts
pages/api/rpc.ts
providers/web3.tsx
utils/use-web3-transport.ts
utilsApi/contractAddressesMetricsMap.ts
utilsApi/rpcFactory.ts

feat: address allow list

---

pages/api/rpc.ts
shared/hooks/use-allowance.ts
shared/hooks/use-balance.ts
utils/use-web3-transport.ts
utilsApi/contractAddressesMetricsMap.ts
utilsApi/rpcFactory.ts

feat: extra rpc checks

---

abi/lidoLocator.abi.json
config/groups/revalidation.ts
features/withdrawals/hooks/contract/useWithdrawalsData.ts
next.config.mjs
server.mjs
utilsApi/fetch-external-manifest.ts
utilsApi/get-default-static-props.ts
utilsApi/nextApiWrappers.ts
utilsApi/rpcFactory.ts

- correct locator abi
- fixed revalidation running on each request
- fixed logging for big RPC request
- added batching when requesting withdrawal statuses(withdrawal page)
- configured http server security defaults

Server Fixes

---

consts/matomo-wallets-events.ts
package.json
yarn.lock

Adds Coinbase Smart Wallet
Related: https://github.com/lidofinance/reef-knot/pull/149

reef-knot 5.6.0 (Coinbase Smart Wallet)

---

pages/api/rpc.ts
server.mjs
shared/hooks/use-balance.ts
utils/use-web3-transport.ts
utilsApi/rpcFactory.ts

- switch on getLogs protection
Please check network and console, before and after connecting wallet. There should not rpc request with getLogs methid  to network with `adress:[]`
Please check not connected wallet with pages wrap and withdrawal

fix: switch on getLogs protection

---

abi/l2-steth.abi.json
abi/l2-wstesth.abi.json
consts/chains.ts
features/wsteth/shared/wallet/wallet.tsx
features/wsteth/wrap/hooks/use-wrap-tx-on-l2-processing.ts
package.json
shared/hooks/use-lido-multichain-fallback-condition.ts
shared/wallet/lido-multichain-fallback/lido-multichain-fallback.tsx
utilsApi/contractAddressesMetricsMap.ts
yarn.lock

- l2 contracts for metric and rpc allow list
- sdk version
- fixed up miltichain banner for wrap page, removed qa helper in favor of config override

fix: rpc allow list

---

features/wsteth/wrap/hooks/use-approve-gas-limit.tsx
shared/hooks/use-is-contract.ts

isContract and gas limit error

fix: isContract and gas limit error

---

features/stake/stake-form/wallet/wallet.tsx
features/withdrawals/claim/wallet/wallet-pending-amount.tsx
shared/components/token-to-wallet/token-to-wallet.tsx
shared/hooks/use-token-address.ts
shared/transaction-modal/tx-stages-composed/tx-stage-operation-succeed-balance-shown.tsx

fix: token to wallet on l2

---

providers/lido-sdk.tsx

Reset internal wagmi state to default chain after wallet is disconnected. This prevents L2 chain utils(gas price) to be used after wallet is disconnected.

Reset to default chain

---

consts/chains.ts
features/rewards/features/top-card/top-card.tsx
shared/hooks/use-dapp-status.ts
shared/wallet/lido-multichain-fallback/lido-multichain-fallback.tsx

Chore: clean up code

---

consts/chains.ts
features/rewards/features/top-card/top-card.tsx
shared/components/layout/header/components/chain-switcher/components/select-icon-tooltip/styles.tsx
shared/components/layout/header/components/chain-switcher/styles.tsx
shared/hooks/use-dapp-status.ts
shared/wallet/lido-multichain-fallback/lido-multichain-fallback.tsx

Fixed the header ChainSwitcher

fix: fix header ChainSwitcher

---

features/wsteth/shared/wallet/wallet.tsx

feat(wrap/unwrap on LL): add banner

---

features/wsteth/shared/wrap-faq/list/do_i_need_to_unwrap_my_wsteth.tsx

fix: faq text

---

next.config.mjs

fix: rpc misconfig

---

features/wsteth/shared/wallet/wallet.tsx
shared/components/layout/header/components/header-wallet.tsx

- fix(header): not show Optimism label
- fix(wrap/unwrap): fix text in the 'wong network' banner

fix: fix not critical fixes

---

IPFS.json
config/external-config/types.ts
config/external-config/utils.ts
features/wsteth/shared/wallet/wallet.tsx

Disables L2 for ledger live and uses config for it

Config feature flags

---

package.json
yarn.lock

Contains this fix:
https://github.com/lidofinance/reef-knot/pull/185

fix: reef-knot 5.7.3

---

IPFS.json

Enabling ipfs config zircuit banner

chore: enable ipfs config zircuit banner

---

features/withdrawals/request/withdrawal-rates/integrations.ts

Update link in paraswap withdrawal 
Only paraswap link is changed

fix: paraswap link

---

package.json
yarn.lock

fix: reef-knot 5.7.5 (wallets metrics)

---

shared/banners/vaults-banner-info/const.ts
shared/banners/vaults-banner-info/vaults-banner-info.tsx

Change defi link to new one.
Landing testnet - https://testnet.fi/steth-in-defi

feat: change defi link in banner

---

features/withdrawals/request/transaction-modal-request/tx-stage-request-success/tx-stage-request-success.tsx
modules/web3/hooks/index.ts
modules/web3/hooks/use-allowance.ts
modules/web3/hooks/use-balance.ts
modules/web3/hooks/use-is-metamask.ts
modules/web3/web3-provider/dapp-chain.tsx
modules/web3/web3-provider/lido-sdk.tsx
modules/web3/web3-provider/sdk-legacy.tsx
package.json
yarn.lock

- prevent async race condition for legacy sdk
- only change chainType when user changes to supported chain
- show add nft helper link for all injected wallets
- force refetch of allowance to bypass laggy user rpcs
- up patch version for wagmi/viem

fix: async condition legacy sdk chainId

---

consts/tokens.ts
consts/tx.ts
features/ipfs/security-status-banner/use-remote-version.ts
features/rewards/components/stats/steth-price-block.tsx
features/rewards/hooks/use-steth-eth-rate.ts
features/rewards/hooks/useGetCurrentAddress.ts
features/stake/stake-form/hooks.ts
features/stake/stake-form/stake-form-context/validation.ts
features/stake/swap-discount-banner/integrations.tsx
features/withdrawals/hooks/contract/useWithdrawalsData.ts
features/wsteth/unwrap/hooks/use-unwrap-gas-limit.ts
features/wsteth/wrap/hooks/use-approve-gas-limit.tsx
features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
modules/web3/hooks/use-stETH-by-wstETH.ts
modules/web3/hooks/use-wstETH-by-stETH.ts
modules/web3/index.ts
modules/web3/web3-provider/dapp-chain.tsx
modules/web3/web3-provider/index.ts
modules/web3/web3-provider/web3-provider.tsx
package.json
shared/components/allowance-data-table-row/allowance-data-table-row.tsx
shared/hook-form/validation/__tests__/validation.tests.ts
shared/hooks/use-eth-usd.ts
utils/get-one-inch-rate.ts
utils/getTokenDisplayName.ts
yarn.lock

- LIDO_TOKENS type
- invariants
- EstimateGas methods from SDK
- comments
- update @lidofinance/lido-ethereum-sdk package version
- useMainnetOnlyWagmi hooks

refactor: batch of changes new SDK, providers

---

consts/token-addresses.ts
features/withdrawals/request/withdrawal-rates/integrations.ts
utils/get-bebop-rate.ts
utils/get-open-ocean-rate.ts
utilsApi/contractAddressesMetricsMap.ts

getRateTokenAddress --> getTokenAddress

refactor: naming

---

features/settings/settings-form/settings-form.tsx
features/withdrawals/claim/form/requests-list/request-item.tsx
features/wsteth/wrap/hooks/use-wrap-gas-limit.ts
package.json
providers/ipfs-info-box-statuses.tsx
shared/hooks/use-protocol-fee.ts
yarn.lock

- refactor(useWrapGasLimit): use the Promise.all + Promise.resolve(null)
- refactor: remove the trick with LIDO_CONTRACT_NAMES

refactor: small updates

---

modules/web3/web3-provider/dapp-chain.tsx
shared/hooks/use-token-address.ts

fix(l2): add token in the wrap/unwrap success modal

fix(l2): add token in the wrap/unwrap success modal

---

shared/components/token-to-wallet/token-to-wallet.tsx

Add token to wallet

---

package.json
yarn.lock

chore: update @lidofinance/lido-ethereum-sdk version

chore: update @lidofinance/lido-ethereum-sdk version

---

scripts/log-environment-variables.mjs

Check EL_RPC_URLS_* only from SUPPORTED_CHAINS (checks before app start)

refactor: check EL_RPC_URLS_* only from SUPPORTED_CHAINS

---

global.d.ts
next.config.mjs
package.json
scripts/log-environment-variables.mjs
utilsApi/metrics/startup-metrics.ts
yarn.lock

chore: update @lidofinance/lido-ethereum-sdk version
feat: add new env, new conditions for env checks and logging
refactor: check EL_RPC_URLS_* only from SUPPORTED_CHAINS

Dev to Main

---

consts/matomo-wallets-events.ts
package.json
yarn.lock

fix: reef-knot imports and deps

---

IPFS.json

chore: ipfs-release-0.76.1

---

IPFS.json

chore: ipfs release 0.76.1 

---

consts/chains.ts
modules/web3/web3-provider/dapp-chain.tsx

**The problem**
The problem happens when a new chain is being deployed.
1. First, the envs with a new supported chain are deployed. The code is planned to be updated a few minutes later.
2. The user opens our widget during deployment after the envs are deployed, but before the code is deployed. The user's wallet is on the network which is being deployed (or the user switches to this new network).
3. The unhandled application error happens. Because lido-ethereum-sdk has its own list of supported networks which is not taken from envs. The widget's code is not updated, so sdk version is not updated, so sdk doesn't support the network being deployed. But the other widget's code thinks that the network is supported, so it is passed to LidoSDK context provider, which throws an error as a …

Fix: check if chain is supported by sdk

---

package.json
yarn.lock

This package version:
- removes old integrity
- changed logic to work with integrities for smoother upgrades of matomo
check if matomo works

feat: update matomo package to 0.50 - proper matomo integrities

---

package.json
yarn.lock

Brings this: https://github.com/lidofinance/lido-ethereum-sdk/pull/215

Use lido-ethereum-sdk v4.4.0-alpha.2

---

shared/components/layout/header/components/chain-switcher/chain-switcher.tsx
shared/components/layout/header/components/chain-switcher/components/chain-switcher-options/chain-switcher-options.tsx
shared/components/layout/header/components/chain-switcher/components/select-icon-tooltip/select-icon-tooltip.tsx

- add `data-testid` for chainSwitcher

add chainSwitcher data-testid

---

.env.example
IPFS.json
modules/web3/hooks/use-aa.ts
package.json
yarn.lock

- Use lido-ethereum-sdk stable release: https://github.com/lidofinance/lido-ethereum-sdk/pull/222
- Update viem, wagmi
- Enable 1inch withdrawal DEX (eth-api released) for Hoodi
- Enable Rewards page for Hoodi
~~Blocked by merging @wagmi/connectors@5.7.13 into main wagmi package:
https://github.com/wevm/wagmi/pull/4617~~
Fixed by resolution
**Requires to check withdrawals claiming via Safe apps browser!**

WIP: Hoodi improvements

---

modules/web3/hooks/use-aa.ts
package.json
yarn.lock

- udpate viem to 2.26.5
- fix AA code to make it backward compatible with different wallets
Tested on:
- Ambire
- Coinbase smart wallet(broken on wallet side)
- MM (with forced AA mode, also broken on wallet side)
- Gnosis.Safe

fix: up viem and fix aa wallets

---

.babelrc
config/networks/networks-map.ts
networks/mainnet.json
package.json
shared/hooks/use-eth-usd.ts
utilsApi/contractAddressesMetricsMap.ts

- Use correct agreator for eth/usd price feed
- return .babelrc because SWC cannot use correct transfroms
- refine browserlist properly to exclude exponent transform rule natively

fix: use correct aggregator

---

features/withdrawals/hooks/useWaitingTime.ts
features/withdrawals/request/form/options/options-picker.tsx
features/withdrawals/request/wallet/wallet-queue-tooltip.tsx

- fix correct passing of wq api params

fix: correct wq api value

---

IPFS.json

Enable Swellchain multichain banner
Related: #644

Enable Swellchain banner

---

modules/web3/web3-provider/web3-provider.tsx

Updates list of wallets shown in the wallets modal

Update wallets list

---

IPFS.json
config/external-config/types.ts
shared/banners/dual-governance-banner/blocked-state.tsx
shared/banners/dual-governance-banner/dual-governance-banner.tsx
shared/banners/dual-governance-banner/styles.ts
shared/banners/dual-governance-banner/warning-state.tsx
shared/hooks/useDGWarningStatus.ts

* [`shared/banners/dual-governance-banner/blocked-state.tsx`](diffhunk://#diff-0bdc6ff8669332a0c829e6b5bc621288c51cc01af8bd71c2beea6ecdc504e4dcR1-R24): Added a new `BlockedState` component to encapsulate the UI for the blocked state of the Dual Governance banner. This improves modularity and reusability.
* [`shared/banners/dual-governance-banner/warning-state.tsx`](diffhunk://#diff-983b2e05a8d32b1beebda17587ab7dfdee3c55e8d28977c3c4647d6931fe1259R1-R18): Introduced a `WarningState` component to handle the warning state UI separately.
* [`shared/banners/dual-governance-banner/dual-governance-banner.tsx`](diffhunk://#diff-6f36f0eb706de5ada0177f479bd3b603da7aa8fccdaa574b78c16b940cad19d9L21-R34): Refactored the banner logic to use the newly created `BlockedState` and `WarningState` components. …

feat: implement dual governance banner states and update feature flags

---

config/networks/networks-map.ts
networks/hoodi-devnet-1.json

chore: add hoodi devnet 1

---

features/withdrawals/hooks/useWaitingTime.ts
features/withdrawals/request/form/options/options-picker.tsx
features/withdrawals/request/form/options/styles.tsx

feat: add wq tooltip

---

features/earn/shared/vault-legal.tsx
features/earn/vault-dvv/faq/dvv-faq.tsx
features/earn/vault-dvv/faq/list/deposit-fee.tsx
features/earn/vault-dvv/faq/list/how-do-i-claim-rewards.tsx
features/earn/vault-dvv/faq/list/what-is-apr-for-dvv.tsx
features/earn/vault-dvv/faq/list/what-is-lido-dvv.tsx
features/earn/vault-dvv/faq/list/why-only-wsteth-on-withdrawal.tsx
features/earn/vault-ggv/faq/list/is-there-a-fee-for-withdrawal.tsx
features/earn/vault-ggv/faq/list/risks-of-depositing.tsx
features/earn/vault-ggv/faq/list/what-is-apy-for-ggv.tsx
features/earn/vault-ggv/vault-page-ggv.tsx

This pull request updates legal disclosures, FAQ content, and risk descriptions for the DVV and GGV vaults to improve clarity and accuracy regarding fees, risks, and reward mechanisms. The most significant changes clarify the nature of protocol fees, slashing risks, and market volatility, and reorganize FAQ components for better user understanding.
**Legal and Fee Disclosure Updates:**
* Updated legal disclosure and FAQ answers in both DVV and GGV vaults to explicitly mention slashing risks and clarify that protocol fees (Lido’s 10% fee on net staking APR) apply only to DVV, not GGV. [[1]](diffhunk://#diff-fbd1c8321d24451c7770e164b7904bd7726ab6a61602405572ff2307a231f685L12-R13) [[2]](diffhunk://#diff-2edbec5b971fdd59e7f3fe9d8aafe2c277c98a2c6afbeb25259360e1621c4815L127-R128) …

feat(earn): update texts

---

features/earn/vault-dvv/faq/list/what-is-apr-for-dvv.tsx
features/earn/vault-dvv/vault-page-dvv.tsx
features/earn/vault-ggv/ggv-apy-hint/ggv-apy-hint.tsx
features/earn/vault-ggv/vault-page-ggv.tsx
shared/components/link-inpage-anchor.tsx

[Earn] improve inpage anchor links

---

features/earn/vault-ggv/consts.tsx
features/earn/vault-ggv/hooks/use-ggv-stats.ts
features/earn/vault-ggv/utils.ts

fix: ggv apy

---

features/earn/vault-dvv/deposit/hooks/use-dvv-deposit.tsx
features/earn/vault-ggv/deposit/hooks/use-ggv-deposit.ts

[earn] add referral

---

features/earn/shared/vault-card/styles.tsx
features/earn/shared/vault-card/vault-card.tsx
features/earn/shared/vault-description/vault-description.tsx
features/earn/vault-dvv/vault-card-dvv.tsx
features/earn/vault-ggv/vault-card-ggv.tsx
features/earn/vault-ggv/vault-page-ggv.tsx

- Fix typo for the GGV Vault on the Vaults List page: premiere -> premier
- Add icons for tokens in the Vaults cards on the Vaults List page (My position)
- Update label: Tokens -> Deposit Tokens
- GGV – update legal disclaimer

Updates for Earn page

---

package.json
yarn.lock

Up react-query

---

IPFS.json

Temporary adds 'stg' vault to IPFS config for dev and testing purposes

[Earn] Add stg to ipfs config

---

IPFS.json

This pull request makes a minor update to the `IPFS.json` configuration file by adding an `apy` field with a value of `{ "type": "weekly" }` to the `ggv` entry in the `earnVaults` array.

feat: add APY type to GGV earnVaults in IPFS.json

---

IPFS.json

- 'strategy' will replace 'stg' vault slug
- 'stg' is temporary left for a smooth transition

Add 'strategy' vault to ipfs.json
